### GENERAL SETTINGS ###

# Site settings
title: Pluu Dev
description: "Android Developer Site"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://pluu.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
paginate: 10
paginate_path: "/blog/page:num/"

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: http://github.com/Pluu
  - title: twitter
    url: https://twitter.com/pluulove

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
author :
  name : pluulove
  email : pluulove@gmail.com
  prev-link : http://blog.naver.com/pluulove84
  comments : pluugithub

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Pluu, Android Developer Blog Site"

plugins: [jekyll-paginate]
